* Placement of the signet
  
  The grey signet in the upper right corner ist not placed well. There
  is a small amount of whitespace on the right edge of each page. The
  signet is stored in a PDF file that is copied from the official
  [[http://verwaltung.uni-koeln.de/abteilung32/content/service/formularschrank/corporate_design/vorlage_fuer_praesentationen/][powerpoint presentation template]] provided by the
  Universitaetsverwaltung, so it should have the right
  dimensions. Scaling it wider, e.g. with width=1.2\pagewidth, does
  not remove the whitespace.
  
  
* Titlepage

  When using \useouthertheme{infolines} (or similar), the boxes
  holding the \section and \subsection names also appear on the
  tilepage. This does not look good and could be avoided by defining a
  seperate titlepage in beamerthemeUzK.sty


* Navigation symbols

  The symbols do not appear. I think that is because they are 'below'
  the footline. It does not bother me much because I have never used
  them myself, but it would be nice to at least retain the
  possibility.


* Define colors for environments

  I already defined the colors for the 'block' environment, but
  environments like 'exampleblock' are not color-defined yet. Beamer
  falls back to a standard green in this case which does not look
  good. This should be done in beamercolorthemeuzk.sty


